### ISSUE TITLE
(ANT-001-002)-Login-Landing Page

### ISSUE THREAD

**Issue by irilnursharief** [PMC-EST/anther_system#18]
1. As a user, I should be able to see the following elements on the landing screen when accessing the app or web interface.
- [x]       1.1. Anther logo at the top right corner of the screen.
- [x]       1.2. Digital PCV text on the left side of the screen, directly across from the logo.
- [x]       1.3. Employee Number text and field
- [x]       1.4. Password text and field
- [x]       1.5. Sign up button
- [x]       1.6. Login button
- [x]       1.7. 'Forgot password' link at the bottom of the screen

**Comment by irilnursharief** [comment]
![Image](https://github.com/user-attachments/assets/18ee188a-471e-42e9-9c29-deadd040c6c7)

[Script-Button-Login.pdf](https://github.com/user-attachments/files/16817868/Script-Button-Login.pdf)
[Script-Button-SignUp.pdf](https://github.com/user-attachments/files/16817876/Script-Button-SignUp.pdf)
[Script-Button-ForgotPassword.pdf](https://github.com/user-attachments/files/16817888/Script-Button-ForgotPassword.pdf)

**Comment by ghost** [comment]
Hi Sir @irilnursharief 

I put the Forgot password link at the bottom side of the page. I suggest to have a "Show" button in the password field for the users to have an option to check their entered password. I just added the "Show" button on the side of the password field for this request. Thank you!

![Image](https://github.com/user-attachments/assets/b454423e-1899-4520-adbe-8d4e2ec8400e)

**Comment by Reggiedel** [comment]
Hi Sir @JohnArvinDugang 

For your verification. Thank you!

**Comment by ghost** [comment]
Hi @Reggiedel 

The "Show" button is still not working. Thanks!

**Comment by ghost** [comment]
This is verified. Thank you!

![Image](https://github.com/user-attachments/assets/ab027b61-282c-4860-84e0-7964fbfdbb4d)
