### ISSUE TITLE
(ANT-001-003)-Login-Sign Up

### ISSUE THREAD

**Issue by irilnursharief** [PMC-EST/anther_system#19]
- [x] 1. Upon clicking the sign-up button, I should see a dialog box with the message "Would you like to create a new user account"?
- [x] 2. If  the user click the "Yes" button it will redirect to Sign Up screen. User to fill in the required details in the Sign Up screen:
- [x]     2.1. Automatically Populated Details:
- [x]     2.2. The system automatically retrieves and displays specific details embedded within it when user input the employee ID number.
- [x]     2.3. These details are not editable by the user.
             *First Name
             *Last Name
             *Company Email
             *Contact No.
             *Company
             *Team
             *Privilege (Requestor, Approver, Custodian, Custodian/Approver, Finance)
             *Custodian Name
             *Custodian Email
             *Custodian's ID
             *Approver's Name
             *Approver's Email
             *Approver's ID

- [x]      2.4. Required Fields and editable by the user.
- [x]      2.5. Password
- [x]                  2.5.1. Password must accept a combination of uppercase letters, lowercase letters, numbers (alphanumeric characters), and special characters.
- [x]                  2.5.2. Password must be between 8 and 12 characters long and include at least one uppercase letter, lowercase letter, number, and special character.
- [x]      2.6. Confirm Password
- [x]                  2.6.1. The confirm password field must accept a combination of uppercase letters, lowercase letters, numbers, and special characters.
- [x]                  2.6.2. The confirm password field must match the password field exactly.
- [x] 3. If any required field is incomplete, the system should display an error message prompting the required information. 
- [ ]      3.1. Error Message: Finance to provide error message
- [x] 4. There should be a disclaimer displayed at the bottom of the Sign Up screen, providing relevant information or terms related to user registration.
- [ ]      4.1. Disclaimer: Finance to provide disclaimer message
- [x] 5. There is "Back" button then system will return in the login screen.
- [x] 6. There is "Create Account" button to create the sign up registration.

Note: Pending HR Request for employee data/list.

Reply to Finance Remarks:
-As discussed with the team previously, all details in the 'Edit Profile' section are auto-populated except for the password. This is because EST will set up or load the employee information in the backend once the data is provided by HR and Finance. We can discuss this further in our weekly update next week.

**Comment by irilnursharief** [comment]
1.
![Image](https://github.com/user-attachments/assets/9be16fa1-9103-4adf-94d0-190a235314c7)

2.
![Image](https://github.com/user-attachments/assets/d25f9a0a-4acc-4806-975d-7b541c30e594)

2.1 - 2.4
![Image](https://github.com/user-attachments/assets/d55aba16-66b2-4686-98bb-b1376358b991)

Employee ID number : 
- If ID is already in the User Master List Table, sign up will not proceed.
- If ID is not in HRIS Employee List Table, sign up will not proceed.

Email Address:
- If ID is not yet in the User Master List Table and exist in HRIS Employee List Table but provided email address did not match the email in HRIS Employee List Table, sign up will not proceed.

All auto populated data is not editable. 

[Script-Button-Verify.pdf](https://github.com/user-attachments/files/16817973/Script-Button-Verify.pdf)

**Comment by irilnursharief** [comment]
2.5 - 2.6.2
![Image](https://github.com/user-attachments/assets/b03ff670-d0ce-4264-8b30-d8c0506dbb19)

3
![Image](https://github.com/user-attachments/assets/260023b3-2457-430a-a87b-0a033afdbd9f)

4 & 6
- Instead of create button that will create the account, Create button will handle the password criteria and open a card window with the terms and condition, and privacy policy.
- User is required to agree before proceeding to account creation.
![Image](https://github.com/user-attachments/assets/74c0ca6a-d1b8-494f-af72-b1a7bba424e6)

5
![Image](https://github.com/user-attachments/assets/73d74210-f86d-401b-a603-0341a2b223fe)


- This script handles the password criteria
[Script-Button-Create.pdf](https://github.com/user-attachments/files/16818166/Script-Button-Create.pdf)

- This script handles the account creation
[Script-Button-Proceed.pdf](https://github.com/user-attachments/files/16818270/Script-Button-Proceed.pdf)

- This script handles how sign up process is being cancelled, Making sure all data in the global fields and global variables does not interrupt with any other running script. 
[Script-Button-Cancel.pdf](https://github.com/user-attachments/files/16818308/Script-Button-Cancel.pdf)

**Comment by Reggiedel** [comment]
Good day, Sir @JohnArvinDugang 

For your verification. Thank you!

**Comment by ghost** [comment]
(ANT-001-003) This is verified and all initial requirements are met except 4.1. Kindly followup the disclaimer message from the finance. Thank you!
