### ISSUE TITLE
(ANT-001-009)-Password-Forgot Password

### ISSUE THREAD

**Issue by irilnursharief** [PMC-EST/anther_system#20]
- [x] 1. Clicking the "Forgot Password" link redirects the user to the Reset Password screen.
- [x] 2. The user inputs a valid employee number and registered email address.
- [x] 3. The system sends a unique reset code to the provided email address.
- [x] 4. After receiving the unique reset code, the user enters the code on the Reset Password screen.
- [x] 5. The user is able to create a new password and confirm it.
- [x] 6. After successfully creating and confirming the new password, the user is redirected back to the login page.
- [ ] 7. User may also receive an email notification informing you that your password has been changed.

**Comment by irilnursharief** [comment]
1
![Image](https://github.com/user-attachments/assets/6cc595f0-077a-491e-8ba6-a056a69bb0c8)
2
![Image](https://github.com/user-attachments/assets/c8527b53-df03-44bd-a121-f4f131480539)
3
![Image](https://github.com/user-attachments/assets/17ed0da0-9517-4a84-ab70-a42c5ff36b96)
4-5
![Image](https://github.com/user-attachments/assets/6fb0d859-5e71-46eb-9044-2018303e5681)
6
![Image](https://github.com/user-attachments/assets/df33fb14-8a0b-4f8a-9fa6-d6ea56831024)
7
![Image](https://github.com/user-attachments/assets/f1d8d2ed-70bd-49bc-86c0-b364c08e0604)

- Handles user employee ID and email verification
[Script-Button-Verify.pdf](https://github.com/user-attachments/files/16818883/Script-Button-Verify.pdf)
- Handles new password update
[Script-Button-SaveNewPassword.pdf](https://github.com/user-attachments/files/16818895/Script-Button-SaveNewPassword.pdf)

**Comment by ghost** [comment]
(ANT-001-009) has been verified that all requirements are met and no modification needed at this point.
