### ISSUE TITLE
(ANT-001-004) Login - Login Credential

### ISSUE THREAD

**Issue by Reggiedel** [PMC-EST/anther_system#22]
- [x] 1. As a user, I should see two text boxes on the login screen:
     - [x]  1.1. One for entering the registered employee ID.
     - [x]  1.2. Another for entering the password.

- [x] 2. Successful Login:
- [x]        2.1. The inputted employee ID and password, the system should authenticate the user.
- [x]        2.2. Upon successful authentication, the user should be immediately redirected to the employee dashboard.

- [x] 3. Unsuccessful Login:
- [x]       3.1. If the user enters incorrect credentials, the system should display an error message indicating that the credentials are invalid.
- [x]       3.2. The user should remain on the login page and not be redirected to the employee dashboard until correct credentials are entered.

**Comment by Reggiedel** [comment]
Good day, Sir @JohnArvinDugang 

For your verification. Thank you!

**Comment by ghost** [comment]
(ANT-001-004) This is verified that all functions are working properly. Thank you!
