### ISSUE TITLE
(ANT-001-005) Login - Access - Requestor

### ISSUE THREAD

**Issue by Reggiedel** [PMC-EST/anther_system#23]
As a requestor, I should be able to see the below modules and request a transaction based on my role.

- [x] 1. Dashboard Module:
- [ ]     * Request Count: The dashboard must display the current number of requests made by the user.
- [ ]       * Finance to decide on the exact concept to be reflected in the count.
- [x]     * Policy Checker: The dashboard must include a policy checker tool to verify compliance with policies.
- [x]                  * The system should automatically calculate the results based on the inputted Project Name, time range, and quantity entered by the requestor.
- [x]     * Transaction List: The dashboard must show a list of all transactions made by the user.
- [x] 2. My Records Module:
- [x]     * View Expense History: The user must be able to view a comprehensive list of their past expense submissions.
- [x]     * Edit Pending Claims: The user must be able to modify pending claims that have not yet been approved or rejected.
- [x]     * Delete Pending Claims: The user must be able to remove pending claims that have not yet been approved or rejected.
- [x] 3. Create Transaction Module:
- [ ]     * Cash Advance Screen: The user must see a form to submit a cash advance request, including fields for necessary details.
- [x]     * Liquidation Screen: The user must see a form to submit a liquidation request, including fields for necessary details.
- [x]     * Reimbursement Screen: The user must see a form to submit a reimbursement request, including fields for necessary details.
- [x]     * Attach Receipts: The user must be able to upload digital copies of receipts when submitting any type of transaction request.

**Comment by Reggiedel** [comment]
Good day, Sir @JohnArvinDugang 

For your verification. Thank you!

**Comment by ghost** [comment]
Request counts are still in progress. (ANT-001-005) is still in progress. Thank you!

![Image](https://github.com/user-attachments/assets/27dee374-2b84-49c6-92a7-fad3971fbf4f)

Cash Advance - The amount of cash that was received by the employee and not yet been liquidated.
Liquidation - Liquidated amount from the cash advance.
Reimbursement - Total amount to be reimbursed to the employee.
